# "basic" workflow github action for the gha project

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "gha-ci-job-1":
  gha-ci-job-1:
    # "ubuntu-latest" == ubuntu-20.04 ('focal'):
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE:
      - uses: actions/checkout@v2

      - name: apt-get update
        run: sudo apt-get update

      - name: apt-get install
        run: sudo apt-get install -y lepton-eda libgtk2.0-dev guile-2.2-dev

      - name: configure
        run: |
          ./autogen.sh
          ./configure --prefix=/usr

      - name: make distcheck
        run:  make distcheck
